import Head from "next/head";

export default function BrowserTab() {
  return (
    <Head>
      <title>Comida Pra Semana</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/cook-book.png" />
    </Head>
  );
};


