import Head from "next/head";

function Aba() {
  return (
    <Head>
      <title>Comida pra semana</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/comida-pra-semana.png" />
    </Head>
  );
}

export default Aba;
