import Head from "next/head";

function Aba() {
  return (
    <Head>
      <title>O que tem pra comer?</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/cook-book.png" />
    </Head>
  );
}

export default Aba;
